# David Lamartina
# lamartid@oregonstate.edu
# Makefile for Program 3: smallsh
# CS344 Spr2019
# Due May 26, 2019

smallsh:
	g++ -g -o smallsh smallsh.c utilities.c commandInput.c commandBuiltIn.c commandExec.c commandSignals.c

clean:
	rm -rf *.o* smallsh
