buildrooms: lamartid.buildrooms.c lamartid.adventure.c
	gcc -g -o lamartid.buildrooms lamartid.buildrooms.c
	gcc -g -o lamartid.adventure lamartid.adventure.c -lpthread

clean:
	rm -rf lamartid.buildrooms lamartid.adventure
